# Generated by Django 4.2.5 on 2023-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_pupil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('mame', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField(default=10)),
                ('class_p', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='pupil',
            name='class_p',
            field=models.IntegerField(default=15),
        ),
    ]
