# Generated by Django 4.2.5 on 2023-11-23 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_workers_alter_pupil_class_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPpersons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=30)),
                ('Home', models.CharField(max_length=30)),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Education', models.CharField(default='Высшее', max_length=30)),
                ('Language', models.CharField(default='English', max_length=30)),
                ('Trips', models.BooleanField(default=True)),
                ('Post', models.CharField(max_length=30)),
                ('Salary', models.IntegerField(default=70000)),
            ],
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
